CREATE DATABASE IF NOT EXISTS vocab_vortex;

USE vocab_vortex;

DROP TABLE IF EXISTS vv_word;
CREATE TABLE IF NOT EXISTS vv_word (
	VVWordID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	VVWordSorted CHAR(6) UNIQUE NOT NULL DEFAULT ''
) engine=InnoDB;

DROP TABLE IF EXISTS vv_subword;
CREATE TABLE IF NOT EXISTS vv_subword (
	VVSubWordID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	VVWordID INT NOT NULL DEFAULT 0,
	VVWordSorted CHAR(6) NOT NULL DEFAULT '',
	VVSubWord VARCHAR(6) NOT NULL DEFAULT '',
	UNIQUE (VVWordSorted,VVSubWord)
) engine=InnoDB;
